### ISSUE TITLE
git checkout is >500MB

### ISSUE THREAD

**Issue by juhp** [UniMath/agda-unimath#689] opened 2023-08-06 21:29 UTC
Not sure if I have bad clone or something, but my git checkout of this repo is over 500MB.
Which seems a little surprising, but maybe it really is that big?
(though the submodule to hott-set-theory is only 7.6MB)

If it's expected perhaps it is worth mentioning in the readme?

**Comment by EgbertRijke** [comment] 2023-08-07 06:00
Thank you for bringing up this issue.

I've garbage-collected and pruned the library in the past, but it is hard to keep the size manageable. Any tips would be very welcome!

**Comment by EgbertRijke** [comment] 2023-08-07 06:04
One of the things we can recommend is to clone only a shallow version of the repository, i.e., without the entire history:

```
git clone --depth 1 git@github.com:UniMath/agda-unimath.git
```

This will create a copy of the library that is only 13MB in size.

**Comment by EgbertRijke** [comment] 2023-08-07 06:12
Hm... but an ordinary fresh clone of agda-unimath without specifying depth is 27MB for me. Now I'm a bit confused about how I could obtain a copy that is over 500MB in size.

**Comment by juhp** [comment] 2023-08-07 07:19
Okay thank you, Egbert - let me check more - possibly something wrong on my side: I was also a bit shocked - I think I originally did the checkout in May 2022 perhaps, but after that it was mostly just sitting there.

**Comment by fredrik-bakke** [comment] 2023-09-17 18:42
Is this issue resolved?

**Comment by EgbertRijke** [comment] 2023-09-17 18:43
I think @VojtechStep wanted to have a look at it.

**Comment by VojtechStep** [comment] 2023-09-17 23:01
I can't reproduce this behavior, the `.git` directory of a deep clean clone is 24MB on my machine. It is possible for that directory to accumulate garbage on one's system over time, but then that requires user action to garbage collect dangling references and repack objects, and that's not an inherent issue with the repository.

**Comment by VojtechStep** [comment] 2023-09-17 23:36
I just ran `git gc --aggressive` on my main checkout where the `.git` directory was 999MB, got it down to 160MB. Considering I have multiple WIP and backup branches, that seems like a reasonable number to me. I think we can close this issue.

**Closed** 2023-09-17 23:37 UTC
Labels: repo-maintenance

**Comment by fredrik-bakke** [comment] 2023-09-17 23:38
Thank you for taking a second look

**Comment by VojtechStep** [comment] 2023-09-17 23:44
Oh nice, and now that I GC'd the git files it also sped up #770 considerably, since that's bottlenecked by the git logs 👌
